version: "3.9"

services:

  ros:
    # xhost +local:root
    image: ghcr.io/seyoungsong/ros-noetic
    container_name: ros
    restart: unless-stopped
    platform: linux/amd64
    privileged: true
    network_mode: host
    init: true
    entrypoint: []
    command: bash -c "sleep infinity"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - ./compose-data/ros-data:/root/data
    working_dir: /root/data
    environment:
      - DISPLAY=:0 # linux: xhost +local:root
      # - DISPLAY=host.docker.internal:0 # macos: xhost +localhost
      - QT_X11_NO_MITSHM=1
      - TZ=Asia/Seoul
