version: "3.8"

services:

  ssh:
    image: ghcr.io/seyoungsong/ssh
    container_name: ssh
    restart: unless-stopped
    init: true
    entrypoint: []
    command: bash -c "service ssh restart && sleep infinity"
    ports:
      # ssh -p 12345 root@localhost
      - "12345:22"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
