version: "3.8"

services:

  ssh:
    image: ghcr.io/seyoungsong/ssh
    container_name: ssh
    restart: unless-stopped
    init: true
    entrypoint: []
    command: service ssh restart && sleep infinity
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
