version: "3.9"

services:

  conda:
    image: ghcr.io/seyoungsong/conda
    container_name: ssh
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    init: true
    entrypoint: []
    command: bash -c "service ssh restart && sleep infinity"
    ports:
      # ssh -p 12345 root@localhost
      - "12345:22"
    volumes:
      - ./compose-data/conda-data:/data
