version: "3.8"

services:
  conda:
    # cd ~/repo/docker/docker/conda && docker compose up --remove-orphans --detach
    # code --folder-uri vscode-remote://attached-container+$(printf conda | xxd -p)/data
    image: ghcr.io/seyoungsong/conda
    container_name: conda
    restart: unless-stopped
    privileged: true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    init: true
    entrypoint: []
    command: bash -c "service ssh restart && sleep infinity"
    ports:
      - "12345:22"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./compose-data/conda-data:/data
    working_dir: /data
    environment:
      # macos: xhost +localhost
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
