version: "3.8"

services:
  rclone:
    image: ghcr.io/seyoungsong/rclone
    container_name: rclone
    restart: unless-stopped
    init: true
    entrypoint: []
    command: sleep infinity
    volumes:
      - ./rclone.conf:/rclone.conf
