version: "3.9"

services:

  seyoung-nvidia:
    # cd ~/repo/docker/docker/nvidia && docker compose up --remove-orphans --detach
    # code --folder-uri vscode-remote://attached-container+$(printf seyoung-nvidia | xxd -p)/data
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: seyoung-nvidia:local
    container_name: seyoung-nvidia
    restart: unless-stopped
    privileged: true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    init: true
    entrypoint: []
    command: bash -c "service ssh restart && sleep infinity"
    ports:
      - "7022:22"
      - "7000-7010"
    volumes:
      - ./compose-data/seyoung-nvidia-data:/data
    working_dir: /data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
