name: goldendict

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/build-and-push-docker-images#path-context
# https://docs.docker.com/build/ci/github-actions/examples/

on:
  push:
  schedule:
    - cron: "0 0 * * 0" # At 00:00 on Sunday.
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          docker run --interactive --privileged -v /artifact:/artifact ghcr.io/seyoungsong/goldendict /bin/bash < .docker/goldendict/build.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GoldenDict.AppImage
          path: /artifact/GoldenDict.AppImage # GoldenDict-5034348-x86_64.AppImage
          if-no-files-found: error
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "GoldenDict (Continuous Build)"
          tag_name: GoldenDict
          files: /artifact/GoldenDict.AppImage
  build-macos:
    # From: https://github.com/xiaoyifang/goldendict/blob/staged/.github/workflows/macos-6.x.yml
    #       https://github.com/xiaoyifang/goldendict/blob/staged/.github/workflows/macos-PR-check.yml
    strategy:
      matrix:
        # os: [macos-11, macos-12]
        # qt_ver: [5.15.2, 6.4.1]
        os: [macos-12] # https://github.com/actions/runner-images/tree/main/images/macos
        qt_ver: [6.4.1] # https://en.wikipedia.org/wiki/Qt_version_history
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout (GoldenDict) # https://github.com/xiaoyifang/goldendict
        uses: actions/checkout@v3
        with:
          repository: xiaoyifang/goldendict
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Qt (Qt5) # https://github.com/jurplel/install-qt-action
        if: ${{ matrix.qt_ver == '5.15.2' }}
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }} # https://github.com/miurahr/aqtinstall
          modules: "qtwebengine"
          setup-python: "false"
      - name: Install Qt (Qt6)
        if: ${{ matrix.qt_ver != '5.15.2' }}
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          modules: "qtwebengine qtwebchannel qtpositioning qt5compat qtmultimedia qtimageformats"
          setup-python: "false"

      - name: Brew
        run: |
          brew uninstall opencc hunspell ffmpeg@5 ffmpeg@4 libtiff xz lzo libogg libvorbis zstd || true
          brew install create-dmg

      - name: Build (Qt5)
        if: ${{ matrix.qt_ver == '5.15.2' }}
        run: |
          qmake CONFIG+=release CONFIG+=zim_support goldendict.pro
          make -j$(nproc)
      - name: Build (Qt6)
        if: ${{ matrix.qt_ver != '5.15.2' }}
        run: |
          qmake CONFIG+=release CONFIG+=zim_support QMAKE_APPLE_DEVICE_ARCHS="x86_64 arm64" goldendict.pro
          make -j$(nproc)

      - name: Package
        run: |
          macdeployqt GoldenDict.app -qmldir=. -verbose=1
          codesign --force --deep -s - GoldenDict.app
          otool -L GoldenDict.app/Contents/MacOS/GoldenDict
          otool -L GoldenDict.app/Contents/Frameworks/lib*
          mkdir tmp
          mv GoldenDict.app ./tmp
          create-dmg --volname "GoldenDict Installer" --volicon "icons/macicon.icns" --window-pos 200 120 --window-size 800 400 --icon-size 100 --icon "GoldenDict.app" 200 190 --hide-extension "GoldenDict.app" --app-drop-link 600 185 --skip-jenkins "GoldenDict.dmg" tmp/
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GoldenDict.dmg
          path: GoldenDict.dmg # /Users/runner/work/actions/actions/GoldenDict.dmg
          if-no-files-found: error
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "GoldenDict (Continuous Build)"
          tag_name: GoldenDict
          files: GoldenDict.dmg
