name: ci

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/build-and-push-docker-images#path-context
# https://docs.docker.com/build/ci/github-actions/examples/
# https://hub.docker.com/settings/security

on:
  # To manually trigger a workflow, use the workflow_dispatch event.
  workflow_dispatch:
  # on push
  push:
  # “At 00:00 on Sunday.”
  schedule:
    - cron: "0 0 * * 0"

env:
  DOCKER_IMAGE: seyoung20/cron-rclone

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .docker
          file: .docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
