# https://github.com/seyoungsong/docker/actions/workflows/remove-old-artifacts.yml

name: Remove old artifacts

on:
  schedule:
    - cron: "1 1 * * *" # “At 01:01.” | https://crontab.guru
  workflow_dispatch:

jobs:
  # https://github.com/c-hive/gha-remove-artifacts#usage
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: "90 seconds" # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
          # Optional inputs
          # skip-tags: true
          # skip-recent: 5

  # https://github.com/kolpav/purge-artifacts-action#usage
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0 # Setting this to 0 will delete all artifacts
